import type { Collection, LinkItem } from "./types";

export const ALL_COLLECTION_ID = "all";

export const collections: Collection[] = [
  { id: "reading", name: "Reading", color: "#ff5a1f" },
  { id: "design", name: "Design", color: "#d6f24b" },
  { id: "build", name: "Build", color: "#7c8cff" },
  { id: "watch-later", name: "Watch later", color: "#9aa3ad" },
  { id: "recipes", name: "Recipes", color: "#e0855a" },
  {
    id: "smart-space",
    name: "Space reads",
    color: "#7c8cff",
    isSmart: true,
    smartQuery: "space",
  },
];

const photo = (seed: string) => `https://picsum.photos/seed/anylink-${seed}/900/700`;

export const links: LinkItem[] = [
  {
    id: "l1",
    url: "https://www.nasa.gov/suit-cost",
    domain: "nasa.gov",
    title: "A full NASA space suit costs $12 mln",
    excerpt:
      "Each Extravehicular Mobility Unit is effectively a one-person spacecraft, and the price tag reflects it.",
    articleText: [
      "Each Extravehicular Mobility Unit (EMU) used on the International Space Station is, in every meaningful sense, a one-person spacecraft. It supplies oxygen, regulates pressure and temperature, and protects against micrometeorites — all while letting an astronaut keep enough dexterity to turn a wrench.",
      "That complexity is why a single suit runs to roughly $12 million, and why NASA has kept the same core design in service for decades rather than replacing it outright.",
      "The agency's newer xEVA suits, built for Artemis moon walks, are contracted separately and priced closer to $1 billion for the full development and production run — a figure that includes years of testing, not just materials.",
      "Refurbishing an existing EMU between missions is cheaper than building new, which is part of why the ISS fleet has stretched so far past its original planned lifespan.",
    ],
    heroImage: photo("suit"),
    tint: "#ff5a1f",
    stripe: "#ffffff",
    initial: "N",
    contentType: "article",
    readingTimeMinutes: 4,
    collectionId: "reading",
    tags: ["space", "longread"],
    size: "L",
    status: "ready",
    createdAt: "2026-08-12T10:00:00.000Z",
    highlights: [
      { id: "h1", quote: "a one-person spacecraft", note: "good framing for the intro" },
    ],
  },
  {
    id: "l2",
    url: "https://arxiv.org/floating-water",
    domain: "arxiv.org",
    title: "Floating water in deep space",
    excerpt: "A new paper models how ice grains cluster inside collapsing molecular clouds.",
    articleText: [
      "A new paper out this week models how ice grains cluster inside collapsing molecular clouds, long before any star or planet has formed.",
      "The simulation suggests that under the right density and temperature conditions, water ice can persist as loosely bound aggregates for millions of years — effectively floating, weightless, in the dark.",
    ],
    heroImage: photo("water"),
    tint: "#7c8cff",
    stripe: "#ffffff",
    initial: "A",
    contentType: "article",
    readingTimeMinutes: 6,
    collectionId: "reading",
    tags: ["science"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-11T09:00:00.000Z",
  },
  {
    id: "l3",
    url: "https://inkandswitch.com/local-first",
    domain: "inkandswitch.com",
    title: "The quiet rise of local-first software",
    excerpt: "Sync engines are getting good enough that offline-first stops being a compromise.",
    articleText: [
      "Sync engines are getting good enough that offline-first stops being a compromise and starts being the obvious default for a certain class of app.",
      "The core idea: keep the source of truth on the device, replicate in the background, and treat the server as one more peer rather than the single point of failure.",
    ],
    heroImage: photo("desk"),
    tint: "#17181b",
    stripe: "#d6f24b",
    initial: "I",
    contentType: "article",
    readingTimeMinutes: 8,
    collectionId: "build",
    tags: ["engineering"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-10T09:00:00.000Z",
  },
  {
    id: "l4",
    url: "https://everything.blog/40-tabs",
    domain: "everything.blog",
    title: "How to read 40 tabs without dying",
    excerpt: "A short case for a triage step between opening a link and reading it.",
    tint: "#d6f24b",
    stripe: "#17181b",
    initial: "E",
    contentType: "article",
    readingTimeMinutes: 3,
    collectionId: "reading",
    tags: ["habits"],
    size: "S",
    status: "ready",
    createdAt: "2026-08-09T09:00:00.000Z",
  },
  {
    id: "l5",
    url: "https://typo.today/grid-systems",
    domain: "typo.today",
    title: "Grid systems, revisited",
    excerpt: "Column grids didn't die with print — they just got quieter.",
    tint: "#9aa3ad",
    stripe: "#ffffff",
    initial: "T",
    contentType: "article",
    readingTimeMinutes: 5,
    collectionId: "design",
    tags: ["design"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-08T09:00:00.000Z",
  },
  {
    id: "l6",
    url: "https://youtube.com/watch?v=foil-setup",
    domain: "youtube.com",
    title: "Foil board setup guide",
    excerpt: "Mast height, fin angle, and the three mistakes every beginner makes.",
    heroImage: photo("foil"),
    tint: "#ff5a1f",
    stripe: "#17181b",
    initial: "Y",
    contentType: "video",
    collectionId: "watch-later",
    tags: ["video", "surf"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-07T09:00:00.000Z",
  },
  {
    id: "l7",
    url: "https://wiki.org/venus-day",
    domain: "wiki.org",
    title: "One day on Venus lasts 243 days",
    excerpt: "Its rotation is so slow that a year passes faster than a day.",
    tint: "#17181b",
    stripe: "#ffffff",
    initial: "W",
    contentType: "article",
    readingTimeMinutes: 2,
    collectionId: "reading",
    tags: ["facts", "space"],
    size: "S",
    status: "ready",
    createdAt: "2026-08-06T09:00:00.000Z",
  },
  {
    id: "l8",
    url: "https://seriouseats.com/sourdough",
    domain: "seriouseats.com",
    title: "Cheap sourdough, no scale needed",
    excerpt: "Cups and a rubber band are all you need to get started.",
    tint: "#d6f24b",
    stripe: "#17181b",
    initial: "S",
    contentType: "article",
    readingTimeMinutes: 7,
    collectionId: "recipes",
    tags: ["recipe"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-05T09:00:00.000Z",
  },
  {
    id: "l9",
    url: "https://css-tricks.com/masonry",
    domain: "css-tricks.com",
    title: "A tiny CSS grid masonry trick",
    excerpt: "grid-auto-rows plus a dense pack gets you 90% of the way there.",
    tint: "#7c8cff",
    stripe: "#17181b",
    initial: "C",
    contentType: "article",
    readingTimeMinutes: 4,
    collectionId: "build",
    tags: ["code"],
    size: "S",
    status: "ready",
    createdAt: "2026-08-04T09:00:00.000Z",
  },
  {
    id: "l10",
    url: "https://skyandtelescope.org/saturn-moons",
    domain: "skyandtelescope.org",
    title: "Saturn has 274 moons now",
    excerpt: "A batch of newly confirmed irregular moons pushes the count well past Jupiter's.",
    tint: "#ff5a1f",
    stripe: "#ffffff",
    initial: "S",
    contentType: "article",
    readingTimeMinutes: 3,
    collectionId: "reading",
    tags: ["space"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-03T09:00:00.000Z",
  },
  {
    id: "l11",
    url: "https://rauno.me/density",
    domain: "rauno.me",
    title: "Interface density is a feeling",
    excerpt: "Density isn't pixel count, it's how confident the layout feels under pressure.",
    tint: "#9aa3ad",
    stripe: "#17181b",
    initial: "R",
    contentType: "article",
    readingTimeMinutes: 5,
    collectionId: "design",
    tags: ["design"],
    size: "S",
    status: "ready",
    createdAt: "2026-08-02T09:00:00.000Z",
  },
  {
    id: "l12",
    url: "https://github.com/self-hosting-archive",
    domain: "github.com",
    title: "Self-hosting a link archive",
    excerpt: "A weekend project that turned into a three-year habit.",
    tint: "#17181b",
    stripe: "#9aa3ad",
    initial: "G",
    contentType: "article",
    readingTimeMinutes: 6,
    collectionId: "build",
    tags: ["build"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "l13",
    url: "https://rozetka.com.ua/apple-iphone-17-pro-max-256-silver/p543550380",
    domain: "rozetka.com.ua",
    title: "Apple iPhone 17 Pro Max 256 GB Silver",
    excerpt: "6.9″ LTPO OLED, A19 Pro, 48 MP triple camera.",
    heroImage: photo("phone"),
    tint: "#7c8cff",
    stripe: "#ffffff",
    initial: "R",
    contentType: "product",
    collectionId: "build",
    tags: ["gear"],
    size: "M",
    status: "ready",
    createdAt: "2026-08-13T09:00:00.000Z",
    product: {
      retailer: "rozetka.com.ua",
      retailerInitial: "R",
      retailerColor: "#00a046",
      code: "543550380",
      price: 74999,
      previousPrice: 79999,
      currency: "₴",
      inStock: true,
      delivery: "Delivery tomorrow",
      rating: 4.8,
      reviewCount: 1204,
      warranty: "12 mo warranty",
      variants: [
        { label: "Silver", swatch: "#e6e7e9" },
        { label: "Graphite", swatch: "#3a3f45" },
        { label: "Copper", swatch: "#c9803e" },
      ],
      specs: [
        { label: "Display", value: "6.9″ LTPO OLED 120 Hz" },
        { label: "Chip", value: "A19 Pro · 6-core" },
        { label: "Storage", value: "256 GB" },
        { label: "Memory", value: "12 GB" },
        { label: "Main camera", value: "48 + 48 + 48 MP" },
        { label: "Front camera", value: "24 MP" },
        { label: "Battery", value: "4 823 mAh" },
        { label: "Charging", value: "40 W wired · 25 W MagSafe" },
        { label: "Body", value: "Aluminium · Ceramic Shield 2" },
        { label: "Weight", value: "233 g" },
        { label: "Water resistance", value: "IP68" },
        { label: "SIM", value: "eSIM only" },
        { label: "OS", value: "iOS 26" },
        { label: "In the box", value: "USB-C cable" },
      ],
      totalSpecCount: 38,
      priceHistory: [
        { date: "2026-07-15", price: 79999 },
        { date: "2026-07-22", price: 79999 },
        { date: "2026-07-29", price: 77500 },
        { date: "2026-08-05", price: 76200 },
        { date: "2026-08-13", price: 74999 },
      ],
      alertThreshold: 70000,
    },
  },
  {
    id: "l14",
    url: "https://vimeo.com/watch/type-foundry",
    domain: "vimeo.com",
    title: "Inside an independent type foundry",
    excerpt: "A short documentary on cutting a typeface from sketch to shipped font file.",
    heroImage: photo("foundry"),
    tint: "#d6f24b",
    stripe: "#17181b",
    initial: "V",
    contentType: "video",
    collectionId: "design",
    tags: ["video", "design"],
    size: "M",
    status: "ready",
    createdAt: "2026-07-30T09:00:00.000Z",
  },
  {
    id: "l15",
    url: "https://arxiv.org/local-first-crdt",
    domain: "arxiv.org",
    title: "CRDTs for people who just want their app to sync",
    excerpt: "A practitioner's tour, not a proofs paper.",
    tint: "#7c8cff",
    stripe: "#17181b",
    initial: "A",
    contentType: "article",
    readingTimeMinutes: 9,
    collectionId: "build",
    tags: ["engineering", "science"],
    size: "S",
    status: "ready",
    createdAt: "2026-07-29T09:00:00.000Z",
  },
  {
    id: "l16",
    url: "https://seriouseats.com/cold-brew",
    domain: "seriouseats.com",
    title: "Cold brew ratios, actually explained",
    excerpt: "Why your homemade batch tastes weaker than the coffee shop's.",
    heroImage: photo("brew"),
    tint: "#e0855a",
    stripe: "#ffffff",
    initial: "S",
    contentType: "article",
    readingTimeMinutes: 4,
    collectionId: "recipes",
    tags: ["recipe"],
    size: "L",
    status: "ready",
    createdAt: "2026-07-28T09:00:00.000Z",
  },
];
