// explicit extension so `node --test src/lib/crawler/check-link.test.ts` resolves
// the chain without a bundler in the way
import { USER_AGENT } from "./fetch-page.ts";
import { NO_ANSWER, PARKED } from "../link-health.ts";

const TIMEOUT_MS = 8_000;
/** Enough of a page to see a parking script or a "for sale" headline; nothing asks
 * for more than this, so a check costs a few KB even on a huge page. */
const SNIFF_BYTES = 16_384;

/** Squatter landing pages are templated by a handful of parking services, and the
 * ones that aren't still have to say they're for sale. Matched against the first
 * `SNIFF_BYTES` of HTML only.
 * ponytail: a keyword list, so a page *about* buying domains reads as parked. It's
 * flagged for review, never deleted, so a false positive costs the user one click. */
const PARKED_MARKERS = [
  "sedoparking.com",
  "parkingcrew.net",
  "bodis.com",
  "afternic.com",
  "hugedomains.com",
  "domain is for sale",
  "domain may be for sale",
  "buy this domain",
  "domain name is for sale",
  "this webpage was generated by the domain owner",
];

/** Returns the HTTP status, or one of the sentinels above. A single ranged GET
 * rather than HEAD-then-maybe-GET: it costs the same round trip, works on the
 * servers that reject HEAD, and is the only way to see a parked page for what it
 * is — those answer 200 like anything else. */
export async function checkLinkStatus(url: string): Promise<number> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      method: "GET",
      signal: controller.signal,
      redirect: "follow",
      headers: { "User-Agent": USER_AGENT, Range: `bytes=0-${SNIFF_BYTES - 1}` },
    });

    // 206 is a server honouring the Range header — the link is alive either way.
    if (res.status === 206) return 200;
    if (res.status >= 400) return res.status;
    // A PDF or an image can't be a parking page, and shouldn't be downloaded to prove it.
    if (!(res.headers.get("content-type") ?? "").includes("html")) return res.status;

    return isParked(await readSlice(res)) ? PARKED : res.status;
  } catch {
    return NO_ANSWER;
  } finally {
    clearTimeout(timeout);
  }
}

export function isParked(html: string): boolean {
  const haystack = html.toLowerCase();
  return PARKED_MARKERS.some((marker) => haystack.includes(marker));
}

/** Reads the head of the body and hangs up — servers that ignore `Range` would
 * otherwise stream the whole page at us. */
async function readSlice(res: Response): Promise<string> {
  if (!res.body) return "";
  const reader = res.body.getReader();
  const chunks: Uint8Array[] = [];
  let size = 0;
  try {
    while (size < SNIFF_BYTES) {
      const { done, value } = await reader.read();
      if (done) break;
      chunks.push(value);
      size += value.length;
    }
  } catch {
    // A truncated read is still worth sniffing.
  } finally {
    await reader.cancel().catch(() => {});
  }
  return new TextDecoder().decode(Buffer.concat(chunks));
}
